sudo: required
services:
  - docker
language: go
go:
  - "1.12"
env:
  - GOOS=linux CGO_ENABLED=0

install: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make unit-test
  - make rest-integration-test
  - make mongo-integration-test
  - make kafka-integration-test
  - make build
  - docker image build -t $DOCKER_USERNAME/myevents-events-service:$TRAVIS_BRANCH .
  - make component-test

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker push $DOCKER_USERNAME/myevents-events-service:$TRAVIS_BRANCH
