sudo: required
services:
  - docker
language: go
go:
  - "1.11"
env:
  - GOOS=linux CGO_ENABLED=0

install: true

script:
  - make unit-test
  - make rest-integration-test
  - make mongo-integration-test
  - make kafka-integration-test
  - make build
  - docker image build -t $DOCKER_USERNAME/myevents-events-service:$TRAVIS_BRANCH .
  - make component-test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker push $DOCKER_USERNAME/myevents-events-service:$TRAVIS_BRANCH
