version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.2
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "ERROR"

  kafka:
    image: confluentinc/cp-kafka:5.1.2
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-secrets:/etc/kafka/secrets
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka=ERROR,kafka.controller=ERROR,kafka.log.LogCleaner=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,kafka.request.logger=ERROR,state.change.logger=ERROR"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.2.1
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    depends_on:
      - zookeeper
      - kafka

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb

  events-service:
    build: .
    ports:
      - 8181:8181
      - 9100:9100
    environment:
      EVENTS_SVC_MONGODB_CONNECTION_URL: 'mongodb://mongodb'
      EVENTS_SVC_MONGODB_DATABASE_NAME: 'events-svc'
      EVENTS_SVC_KAFKA_BROKERS: 'kafka:29092'
      EVENTS_SVC_OUTBOUND_TOPIC: 'myevents.events'
      EVENTS_SVC_REST_API_TCP_ADDRESS: ':8181'
      EVENTS_SVC_METRICS_TCP_ADDRESS: ':9100'
    restart: always

volumes:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
  kafka-secrets: